### ISSUE TITLE
Cannot save certain settings. 

### ISSUE THREAD

**Issue by Zarainia** [RedFantom/GSF-Parser#55] opened 2017-02-21 18:14 UTC
I cannot save certain settings in the settings tab. These are: "enable overlay for real-time parsing", "only display overlay in a GSF match", "auto-upload combatlogs to the server", and "connect to server for player identification". I am not able to enable these settings. (I'm not sure whether the server stuff is supposed to be working but it seems like the overlay is?)

For "enable overlay" and "auto-upload combatlogs", when I click "save" after changing the setting, a loading bar pops up and after it's done, the setting is reset. For the "only display overlay in a GSF match", a notice pops up, and when I click okay, the loading bar appears, finishes, and the setting is reset. For "connect to server for player identification", a popup tells me it needs to be restarted, but only if it's the first time I've tried to change the setting. Then, the loading bar appears and the setting is reset like the other ones. (Restarting does not cause the setting to be what I saved.) The restart message also appears sometimes for the "enable overlay" option, but not always. Also, "enable overlay" sometimes starts off as enabled, and then it can be disabled, but not enabled again after that. 

![image](https://cloud.githubusercontent.com/assets/14959769/23178211/96129568-f837-11e6-980e-3211ec5106cc.png)

Debug just says "settings read, settings written, save_settings called".

**Comment by RedFantom** [comment] 2017-02-21 19:31
The `[DEBUG]` messages do not display specifically what settings are changed. I will try to create a `save_single_setting()` function for #53. I will try to reproduce the problem on my Windows 10 virtual machine. The fact that your settings reset after changing means the settings are not written to the configuration file correctly. While it should not make any difference (when does this actually ever come true?), could you try running the GSF Parser as administrator for me?

**Comment by Zarainia** [comment] 2017-02-22 02:40
I tried running it as administrator, and it did not change anything.

**Comment by RedFantom** [comment] 2017-02-23 11:05
Could you try deleting your `settings.ini` file from the `%AppData%\Local\GSF Parser` for me? Then you will get the default settings written again and it might work.

**Comment by RedFantom** [comment] 2017-03-12 20:18
Bump @Zarainia

**Comment by Zarainia** [comment] 2017-03-12 21:08
Sorry, I didn't see this. I tried it and it's doing the same thing. Sometimes the pop-up shows, and sometimes not.

**Comment by RedFantom** [comment] 2017-03-13 15:51
No problem. With the most recent version of `master`, I have been able to reproduce this issue by changing the settings for uploading. I'll search for a bug in the code.

**Comment by RedFantom** [comment] 2017-03-13 17:10
Could you try again now that I've fixed that setting? Maybe it's related to the other problems somehow? I am unable to find other problems, and I can't reproduce it anymore with the commit...

**Comment by Zarainia** [comment] 2017-03-14 01:28
Unfortunately, it doesn't seem to have changed anything.

**Comment by Zarainia** [comment] 2017-03-14 01:34
Another interesting thing I noticed was that the button says the overlay is disabled, while in settings.ini, the setting is 1 (which I assume is true?). Here is the settings file, by the way (converted to .txt). There is also a value of PY_VAR15, which is kind of strange. Not sure if that's what it's supposed to be. 

[settings.txt](https://github.com/RedFantom/GSF-Parser/files/840038/settings.txt)

**Comment by RedFantom** [comment] 2017-03-14 11:57
The `PY_VAR15` problem was solved in the commit, so if you save the settings again with the branch `settings`, it should at least make  that disappear. I'll take a look at your settings file this afternoon.

**Comment by RedFantom** [comment] 2017-03-14 20:38
Oh, that's interesting! The settings file says `1` and `0`, while it should be `False` or `True`. That's the error! Well spotted, @Zarainia . It's quite weird, because my settings file really does say `True` and `False`, and the settings are saved correctly. In my Windows 7 VM, however, this is no the case and it's `1` or `0`. Could you try again with this new commit?

**Comment by Zarainia** [comment] 2017-03-15 01:56
I downloaded the settings branch, and it didn't seem to have an effect on the problem.

**Comment by RedFantom** [comment] 2017-03-16 19:02
All right, maybe we should switch from `RawConfigParser` to a normal `ConfigParser`. I don't have time now, but I'll try to make time for it as soon as I can.

**Comment by RedFantom** [comment] 2017-06-04 20:34
As far as I've tested, the issue is now fixed.

**Closed by RedFantom** 2017-06-04 20:34 UTC
Labels: bug
