### ISSUE TITLE
Selecting "All combatlogs/matches/spawns" does not show all of them. 

### ISSUE THREAD

**Issue by Zarainia** [RedFantom/GSF-Parser#56] opened 2017-02-22 16:35 UTC
I'm not sure what the expected behaviour is, but this doesn't seem right. Selecting "all combatlogs" shows the same matches as selecting the last combatlog in the list (and only those), selecting "all matches" shows the same spawns as the last match in the list (and only those), and selecting "all spawns" shows the same statistics as the last spawn in the list. 

![image](https://cloud.githubusercontent.com/assets/14959769/23221313/bd938fdc-f8f2-11e6-8e26-04fa8e236df3.png)
![image](https://cloud.githubusercontent.com/assets/14959769/23221336/cb71d424-f8f2-11e6-8c4f-392a46857519.png)

**Comment by RedFantom** [comment] 2017-02-22 17:58
That indeed doesn't seem right. When selecting `All CombatLogs`, a splash screen with a `ttk.Progressbar` should appear, and then it should show very, very high numbers as it shows the statistics for all CombatLogs found put together. When selecting `All matches`, it should parse all the matches found in a CombatLog. When selecting `All spawns`, it should parse all spawns found in a match. Clearly having the same statistics for the last spawn as for the whole match is not right. I'll boot up my VM right now.

**Comment by RedFantom** [comment] 2017-02-22 18:14
It works quite fine in my Windows 10 VM, thought without the `plastik` theme, admittedly. Are you sure you are generating a `Double-Button-1` mouse event?
![1](https://cloud.githubusercontent.com/assets/15170036/23225681/102e0f34-f933-11e6-84d4-f748103eb1b4.png)
![2](https://cloud.githubusercontent.com/assets/15170036/23225682/1031555e-f933-11e6-9eea-cb189d4911e0.png)

**Comment by Zarainia** [comment] 2017-02-22 18:18
I am clicking on it the same way as individual matches and stuff, yes. It did the same thing before, without the theme, as well. (Wow, everything seems to be breaking for me for some reason!)

**Comment by RedFantom** [comment] 2017-02-22 18:41
Could you provide me with the whole CombatLog? Then I can verify whether it is a problem with the CombatLog, or with the actual GSF Parser with some structural error.

**Comment by Zarainia** [comment] 2017-02-22 21:45
Here is my CombatLogs folder. 

[CombatLogs.zip](https://github.com/RedFantom/GSF-Parser/files/794888/CombatLogs.zip)

**Comment by RedFantom** [comment] 2017-02-23 10:10
While I did find a new problem, being that the ship counting is off for spawns when selecting `All spawns`, I am unable reproduce your issue with the latest version of the `development` branch, or even v2.5.3 of the `master` branch... It seems you did activate the GSF Parser correctly by double clicking on each item, given that some items have the background `lightgrey` meaning `spawn_update` was called. The weird thing is that your version also doesn't elimate ships from the possible ships list...

**Comment by Zarainia** [comment] 2017-02-23 13:43
I think it's just this spawn in particular where it didn't eliminate the possible ships, since it was short and I didn't use any abilities. That is working fine usually.

**Comment by RedFantom** [comment] 2017-02-23 14:43
OK, that would explain it, indeed. But as I can not reproduce this issue, I'm going to assume that it was a one-time event. You can do the honours on closing this issue, @Zarainia, unless you think it's still worth investigating further? I really can't think of anything else to check...

**Comment by Zarainia** [comment] 2017-02-23 16:19
Turns out it was the `numbers` being a string rather than an int issue again. To determine whether "all" of something was selected, the code is checking whether `self.file_box.curselection()` is `(0,)`, but of course, it wouldn't be that if the first element is a string. Might be worth looking into that function and why it's returning a string, but adding `or self.file_box.curselection() == ('0',)` (and similar things for the `match_box` and `spawn_box`) should fix the problem.

**Comment by Zarainia** [comment] 2017-02-23 16:30
Though, I noticed now that my damage ratio when selecting all files is shown as 0.4:1, which is kind of odd considering that all the individual files I looked at had a damage ratio of over 1:1... not sure what's up with that.

**Closed** 2017-02-23 16:53 UTC
Labels: bug

**Comment by RedFantom** [comment] 2017-02-23 17:05
Wow, well spotted! That also explains why I was unable to reproduce the issue! Would you also do a commit for the `ddealt`-`dtaken` mixup?
